import Foundation
import TandhaCore

/// Generates a nested Swift enum tree of compile-time-safe identifier constants
/// from an `AutomationModel`.
///
/// ```swift
/// let source = SwiftEnumGenerator().generate(model)
/// ```
/// produces, for the login/dashboard example:
/// ```swift
/// public enum AutomationID {
///     public enum login {
///         public static let usernameField = "login.username_field"
///         public static let submitButton = "login.submit_button"
///     }
/// }
/// ```
public struct SwiftEnumGenerator {
    /// Name of the generated root enum.
    public var rootName: String
    /// Access level for the generated declarations.
    public var accessLevel: String
    /// When true, emit `///` doc comments from entry `description` / `screen`.
    public var emitDocComments: Bool
    /// Header line stamped at the top of the file.
    public var header: String

    public init(
        rootName: String = "AutomationID",
        accessLevel: String = "public",
        emitDocComments: Bool = true,
        header: String = "// Generated by tandha — do not edit."
    ) {
        self.rootName = rootName
        self.accessLevel = accessLevel
        self.emitDocComments = emitDocComments
        self.header = header
    }

    /// Render the full Swift source for `model`.
    public func generate(_ model: AutomationModel) -> String {
        var lines: [String] = []
        lines.append(header)
        lines.append("")
        lines.append("\(accessLevel) enum \(SwiftIdentifier.groupName(rootName)) {")
        emit(nodes: model.root, indent: 1, into: &lines)
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    private func emit(nodes: [AutomationNode], indent: Int, into lines: inout [String]) {
        let pad = String(repeating: "    ", count: indent)
        var usedNames: Set<String> = []

        for node in nodes {
            switch node {
            case .group(let name, _, let children):
                let enumName = unique(SwiftIdentifier.groupName(name), in: &usedNames)
                lines.append("\(pad)\(accessLevel) enum \(enumName) {")
                emit(nodes: children, indent: indent + 1, into: &lines)
                lines.append("\(pad)}")
            case .leaf(let entry):
                if emitDocComments {
                    for comment in docComments(for: entry) { lines.append("\(pad)\(comment)") }
                }
                let constName = unique(SwiftIdentifier.camelCased(node.name), in: &usedNames)
                lines.append("\(pad)\(accessLevel) static let \(constName) = \"\(escape(entry.identifier))\"")
            }
        }
    }

    private func docComments(for entry: AutomationIDEntry) -> [String] {
        var comments: [String] = []
        if let description = entry.description, !description.isEmpty {
            comments.append("/// \(description)")
        }
        if let screen = entry.screen, !screen.isEmpty {
            comments.append("/// Screen: \(screen)")
        }
        return comments
    }

    /// Deduplicate member names within one scope by appending `_2`, `_3`, …
    private func unique(_ base: String, in used: inout Set<String>) -> String {
        var candidate = base
        var suffix = 2
        while used.contains(candidate) {
            candidate = "\(base)_\(suffix)"
            suffix += 1
        }
        used.insert(candidate)
        return candidate
    }

    private func escape(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }
}
