import Foundation
import TandhaCore

/// Emits an Appium/Katalon-friendly Java page-object class of `By` locators that
/// mirror the contract's namespace tree.
///
/// ```java
/// public static final class Login {
///     public static final By usernameField =
///         AppiumBy.accessibilityId("login.username_field");
/// }
/// ```
public struct JavaPageObjectExporter: Exporter {
    public static let formatName = "java"
    public static let fileExtension = "java"

    /// Java package for the generated class.
    public var packageName: String
    /// Name of the top-level generated class.
    public var className: String

    public init(packageName: String = "com.example.automation", className: String = "AutomationIDs") {
        self.packageName = packageName
        self.className = className
    }

    public func export(_ model: AutomationModel) -> String {
        var lines: [String] = []
        lines.append("// Generated by tandha — do not edit.")
        lines.append("package \(packageName);")
        lines.append("")
        lines.append("import io.appium.java_client.AppiumBy;")
        lines.append("import org.openqa.selenium.By;")
        lines.append("")
        lines.append("public final class \(pascal(className)) {")
        lines.append("    private \(pascal(className))() {}")
        emit(nodes: model.root, indent: 1, into: &lines)
        lines.append("}")
        return lines.joined(separator: "\n") + "\n"
    }

    private func emit(nodes: [AutomationNode], indent: Int, into lines: inout [String]) {
        let pad = String(repeating: "    ", count: indent)
        for node in nodes {
            switch node {
            case .group(let name, _, let children):
                let cls = pascal(name)
                lines.append("\(pad)public static final class \(cls) {")
                lines.append("\(pad)    private \(cls)() {}")
                emit(nodes: children, indent: indent + 1, into: &lines)
                lines.append("\(pad)}")
            case .leaf(let entry):
                let field = camel(node.name)
                lines.append("\(pad)public static final By \(field) = AppiumBy.accessibilityId(\(quote(entry.identifier)));")
            }
        }
    }

    // MARK: naming

    private func parts(_ raw: String) -> [String] {
        raw.split(whereSeparator: { $0 == "_" || $0 == "-" || $0 == " " || $0 == "." }).map(String.init)
    }

    private func camel(_ raw: String) -> String {
        let p = parts(raw)
        guard let first = p.first else { return "_" }
        var result = first.prefix(1).lowercased() + first.dropFirst()
        for part in p.dropFirst() { result += part.prefix(1).uppercased() + part.dropFirst() }
        return leadingSafe(result)
    }

    private func pascal(_ raw: String) -> String {
        parts(raw).map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined().isEmpty
            ? "_"
            : leadingSafe(parts(raw).map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined())
    }

    private func leadingSafe(_ s: String) -> String {
        guard let first = s.first else { return "_" }
        return first.isNumber ? "_" + s : s
    }

    private func quote(_ s: String) -> String {
        let escaped = s.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}
